###  Import Necessary Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [15]:
df =sns.load_dataset("dots")

In [16]:
df.head()

  align choice  time  coherence  firing_rate
0  dots     T1   -80        0.0    33.189967
1  dots     T1   -80        3.2    31.691726
2  dots     T1   -80        6.4    34.279840
3  dots     T1   -80       12.8    32.631874
4  dots     T1   -80       25.6    35.060487

In [17]:
df.shape

(848, 5)

In [18]:
df.isnull().sum()

align          0
choice         0
time           0
coherence      0
firing_rate    0
dtype: int64

In [31]:
df.head()

  align choice  time  coherence  firing_rate
0  dots     T1   -80        0.0    33.189967
1  dots     T1   -80        3.2    31.691726
2  dots     T1   -80        6.4    34.279840
3  dots     T1   -80       12.8    32.631874
4  dots     T1   -80       25.6    35.060487

### Seprate X,y Variable

In [32]:
X =df[["coherence"]]
y =df["firing_rate"]

In [34]:
X

     coherence
0          0.0
1          3.2
2          6.4
3         12.8
4         25.6
..         ...
843        3.2
844        6.4
845       12.8
846       25.6
847       51.2

[848 rows x 1 columns]

In [35]:
y

0      33.189967
1      31.691726
2      34.279840
3      32.631874
4      35.060487
         ...
843    33.281734
844    27.583979
845    28.511530
846    27.009804
847    30.959302
Name: firing_rate, Length: 848, dtype: float64

### Train test Spilt

In [36]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y ,test_size=0.20,random_state=1)
X_train.shape ,X_test.shape ,y_train.shape ,y_test.shape

((678, 1), (170, 1), (678,), (170,))

### Create model

In [37]:
from sklearn.linear_model import LinearRegression
model =LinearRegression()
model.fit(X_train ,y_train)
ypred =model.predict(X_test)
ypred

array([40.95525575, 40.64094735, 40.32663895, 38.44078854, 40.64094735,
       40.32663895, 38.44078854, 40.32663895, 39.69802215, 35.92632133,
       40.32663895, 35.92632133, 40.32663895, 38.44078854, 39.69802215,
       40.32663895, 40.64094735, 38.44078854, 39.69802215, 40.95525575,
       40.64094735, 35.92632133, 40.64094735, 39.69802215, 39.69802215,
       35.92632133, 40.64094735, 40.32663895, 40.32663895, 39.69802215,
       40.64094735, 39.69802215, 40.95525575, 40.95525575, 40.64094735,
       39.69802215, 35.92632133, 38.44078854, 39.69802215, 40.32663895,
       40.32663895, 35.92632133, 39.69802215, 39.69802215, 40.95525575,
       38.44078854, 35.92632133, 40.64094735, 40.64094735, 40.64094735,
       40.32663895, 38.44078854, 40.95525575, 38.44078854, 40.32663895,
       40.95525575, 38.44078854, 40.95525575, 38.44078854, 38.44078854,
       40.64094735, 40.64094735, 40.64094735, 38.44078854, 40.95525575,
       39.69802215, 35.92632133, 40.95525575, 39.69802215, 35.92632133,
       40.32663895, 40.95525575, 40.64094735, 35.92632133, 40.95525575,
       35.92632133, 35.92632133, 35.92632133, 40.64094735, 40.95525575,
       40.32663895, 40.95525575, 40.95525575, 40.95525575, 39.69802215,
       39.69802215, 39.69802215, 40.64094735, 40.64094735, 40.32663895,
       40.95525575, 40.64094735, 40.95525575, 40.32663895, 40.32663895,
       40.32663895, 40.95525575, 35.92632133, 40.64094735, 40.95525575,
       35.92632133, 40.95525575, 40.64094735, 40.32663895, 39.69802215,
       40.95525575, 40.95525575, 39.69802215, 40.32663895, 40.64094735,
       40.64094735, 35.92632133, 39.69802215, 40.95525575, 35.92632133,
       40.32663895, 40.64094735, 40.95525575, 40.32663895, 40.95525575,
       40.32663895, 35.92632133, 35.92632133, 40.95525575, 40.64094735,
       38.44078854, 39.69802215, 39.69802215, 38.44078854, 35.92632133,
       40.32663895, 39.69802215, 35.92632133, 35.92632133, 39.69802215,
       39.69802215, 40.95525575, 38.44078854, 35.92632133, 39.69802215,
       38.44078854, 40.95525575, 40.64094735, 38.44078854, 38.44078854,
       40.95525575, 40.64094735, 40.32663895, 40.95525575, 35.92632133,
       35.92632133, 40.32663895, 40.64094735, 40.64094735, 40.95525575,
       40.95525575, 39.69802215, 38.44078854, 40.64094735, 39.69802215,
       40.32663895, 40.64094735, 40.64094735, 40.64094735, 40.64094735,
       39.69802215, 38.44078854, 40.32663895, 40.95525575, 38.44078854])

In [39]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mse =mean_squared_error(y_test ,ypred)
mse

146.3279395072467

In [40]:
mae =mean_absolute_error(y_test ,ypred)
mae

9.108846968999575

In [41]:
r2_score(y_test ,ypred)

0.02120725532080714

### Pickle model

In [42]:
import pickle
pickle.dump(model ,open("dot_regressor.pkl","wb"))

In [43]:
model =pickle.load(open("dot_regressor.pkl","rb"))

In [44]:
model.predict(X_train)

array([40.64094735, 35.92632133, 40.95525575, 40.95525575, 40.64094735,
       40.32663895, 38.44078854, 40.32663895, 39.69802215, 40.95525575,
       40.64094735, 40.95525575, 40.32663895, 35.92632133, 40.95525575,
       35.92632133, 40.32663895, 40.95525575, 40.95525575, 35.92632133,
       40.64094735, 39.69802215, 35.92632133, 40.64094735, 35.92632133,
       39.69802215, 40.32663895, 38.44078854, 40.95525575, 40.95525575,
       40.95525575, 39.69802215, 40.64094735, 40.64094735, 40.95525575,
       40.95525575, 39.69802215, 40.32663895, 39.69802215, 40.32663895,
       40.95525575, 35.92632133, 39.69802215, 40.64094735, 40.95525575,
       38.44078854, 40.32663895, 40.95525575, 39.69802215, 38.44078854,
       40.32663895, 40.64094735, 40.95525575, 40.95525575, 40.64094735,
       40.32663895, 40.95525575, 39.69802215, 38.44078854, 40.64094735,
       40.32663895, 39.69802215, 40.64094735, 40.32663895, 40.95525575,
       40.32663895, 40.64094735, 40.95525575, 40.32663895, 40.95525575,
       38.44078854, 38.44078854, 38.44078854, 38.44078854, 40.95525575,
       40.64094735, 40.32663895, 39.69802215, 40.95525575, 40.32663895,
       40.64094735, 40.95525575, 38.44078854, 40.32663895, 35.92632133,
       38.44078854, 35.92632133, 40.64094735, 40.95525575, 40.32663895,
       40.64094735, 40.95525575, 40.32663895, 38.44078854, 40.95525575,
       40.32663895, 40.64094735, 39.69802215, 39.69802215, 40.95525575,
       40.32663895, 38.44078854, 38.44078854, 40.95525575, 38.44078854,
       40.64094735, 39.69802215, 40.64094735, 40.64094735, 40.95525575,
       38.44078854, 39.69802215, 39.69802215, 38.44078854, 40.32663895,
       40.64094735, 35.92632133, 40.32663895, 40.64094735, 39.69802215,
       40.95525575, 40.32663895, 40.95525575, 40.32663895, 40.95525575,
       39.69802215, 40.95525575, 40.95525575, 40.32663895, 40.64094735,
       40.64094735, 38.44078854, 38.44078854, 40.64094735, 38.44078854,
       40.95525575, 40.32663895, 35.92632133, 35.92632133, 35.92632133,
       38.44078854, 38.44078854, 40.32663895, 40.64094735, 40.32663895,
       40.32663895, 38.44078854, 40.32663895, 40.64094735, 40.64094735,
       40.64094735, 39.69802215, 39.69802215, 35.92632133, 40.95525575,
       40.64094735, 40.95525575, 40.95525575, 40.32663895, 39.69802215,
       40.95525575, 40.64094735, 40.64094735, 39.69802215, 38.44078854,
       40.95525575, 38.44078854, 40.32663895, 35.92632133, 40.32663895,
       35.92632133, 39.69802215, 39.69802215, 40.64094735, 39.69802215,
       40.32663895, 40.32663895, 39.69802215, 40.32663895, 40.32663895,
       39.69802215, 39.69802215, 35.92632133, 39.69802215, 39.69802215,
       39.69802215, 38.44078854, 40.64094735, 40.64094735, 39.69802215,
       40.95525575, 40.32663895, 40.95525575, 40.64094735, 38.44078854,
       38.44078854, 40.95525575, 40.64094735, 40.64094735, 40.95525575,
       39.69802215, 38.44078854, 39.69802215, 40.32663895, 38.44078854,
       40.95525575, 40.32663895, 40.32663895, 39.69802215, 40.95525575,
       39.69802215, 40.95525575, 39.69802215, 40.95525575, 39.69802215,
       40.95525575, 40.64094735, 40.64094735, 40.64094735, 40.64094735,
       40.95525575, 40.32663895, 38.44078854, 40.95525575, 40.95525575,
       40.95525575, 38.44078854, 35.92632133, 40.95525575, 40.95525575,
       40.95525575, 38.44078854, 39.69802215, 40.95525575, 40.95525575,
       39.69802215, 40.32663895, 40.95525575, 40.95525575, 38.44078854,
       39.69802215, 40.95525575, 40.95525575, 38.44078854, 35.92632133,
       40.64094735, 40.95525575, 40.95525575, 38.44078854, 38.44078854,
       40.64094735, 39.69802215, 40.95525575, 40.64094735, 40.32663895,
       35.92632133, 39.69802215, 40.95525575, 40.95525575, 40.32663895,
       40.95525575, 40.32663895, 40.95525575, 40.95525575, 40.95525575,
       35.92632133, 39.69802215, 40.95525575, 40.95525575, 40.32663895,
       40.95525575, 38.44078854, 35.92632133, 38.44078854, 40.64094735,
       40.32663895, 40.95525575, 38.44078854, 39.69802215, 39.69802215,
       40.95525575, 40.64094735, 40.64094735, 40.64094735, 38.44078854,
       40.64094735, 40.95525575, 40.32663895, 40.32663895, 40.95525575,
       40.32663895, 40.64094735, 40.95525575, 40.32663895, 39.69802215,
       40.64094735, 39.69802215, 39.69802215, 40.95525575, 39.69802215,
       40.64094735, 35.92632133, 40.64094735, 40.64094735, 40.95525575,
       40.95525575, 38.44078854, 40.95525575, 40.32663895, 39.69802215,
       40.64094735, 39.69802215, 39.69802215, 40.95525575, 40.95525575,
       40.32663895, 40.32663895, 40.64094735, 40.32663895, 40.64094735,
       35.92632133, 40.32663895, 38.44078854, 39.69802215, 39.69802215,
       40.64094735, 40.95525575, 39.69802215, 38.44078854, 40.32663895,
       40.95525575, 40.32663895, 40.64094735, 39.69802215, 35.92632133,
       39.69802215, 39.69802215, 35.92632133, 40.32663895, 39.69802215,
       40.32663895, 40.32663895, 39.69802215, 40.64094735, 40.32663895,
       40.32663895, 39.69802215, 40.64094735, 40.64094735, 35.92632133,
       38.44078854, 40.95525575, 39.69802215, 40.95525575, 39.69802215,
       40.32663895, 40.64094735, 38.44078854, 40.64094735, 40.95525575,
       39.69802215, 40.64094735, 39.69802215, 39.69802215, 35.92632133,
       40.32663895, 35.92632133, 35.92632133, 35.92632133, 35.92632133,
       38.44078854, 40.64094735, 39.69802215, 35.92632133, 35.92632133,
       39.69802215, 39.69802215, 40.64094735, 40.95525575, 35.92632133,
       40.95525575, 40.32663895, 40.32663895, 40.32663895, 40.32663895,
       40.64094735, 40.64094735, 40.95525575, 40.64094735, 40.32663895,
       40.32663895, 40.32663895, 39.69802215, 40.64094735, 40.64094735,
       35.92632133, 38.44078854, 40.32663895, 40.64094735, 38.44078854,
       38.44078854, 40.32663895, 38.44078854, 40.32663895, 40.64094735,
       40.32663895, 40.95525575, 40.64094735, 35.92632133, 38.44078854,
       40.32663895, 39.69802215, 38.44078854, 38.44078854, 39.69802215,
       39.69802215, 39.69802215, 40.32663895, 40.32663895, 40.32663895,
       38.44078854, 40.64094735, 38.44078854, 40.95525575, 40.64094735,
       38.44078854, 40.64094735, 40.32663895, 40.32663895, 40.64094735,
       40.95525575, 40.32663895, 40.95525575, 38.44078854, 38.44078854,
       40.32663895, 35.92632133, 40.64094735, 38.44078854, 40.32663895,
       40.64094735, 35.92632133, 40.95525575, 38.44078854, 40.95525575,
       40.95525575, 35.92632133, 35.92632133, 40.64094735, 40.64094735,
       38.44078854, 39.69802215, 40.64094735, 40.64094735, 35.92632133,
       40.32663895, 35.92632133, 40.95525575, 35.92632133, 40.95525575,
       40.95525575, 39.69802215, 40.64094735, 40.32663895, 38.44078854,
       40.32663895, 35.92632133, 40.64094735, 40.32663895, 40.95525575,
       38.44078854, 38.44078854, 39.69802215, 40.64094735, 40.32663895,
       40.64094735, 40.95525575, 38.44078854, 40.95525575, 40.95525575,
       35.92632133, 39.69802215, 40.64094735, 39.69802215, 40.32663895,
       40.64094735, 39.69802215, 40.32663895, 40.32663895, 40.95525575,
       38.44078854, 40.32663895, 35.92632133, 39.69802215, 40.64094735,
       40.32663895, 40.64094735, 38.44078854, 40.64094735, 35.92632133,
       40.95525575, 39.69802215, 40.64094735, 40.95525575, 35.92632133,
       40.64094735, 39.69802215, 40.32663895, 40.95525575, 40.32663895,
       40.95525575, 40.95525575, 40.95525575, 40.64094735, 40.64094735,
       38.44078854, 40.64094735, 40.95525575, 38.44078854, 39.69802215,
       40.95525575, 40.32663895, 38.44078854, 39.69802215, 40.95525575,
       35.92632133, 40.95525575, 40.64094735, 40.32663895, 40.64094735,
       40.64094735, 38.44078854, 40.32663895, 39.69802215, 40.32663895,
       38.44078854, 40.64094735, 40.64094735, 40.32663895, 40.95525575,
       39.69802215, 40.95525575, 40.64094735, 39.69802215, 40.32663895,
       39.69802215, 40.32663895, 40.95525575, 40.95525575, 40.64094735,
       40.64094735, 40.32663895, 40.32663895, 38.44078854, 39.69802215,
       35.92632133, 38.44078854, 39.69802215, 40.95525575, 38.44078854,
       40.64094735, 35.92632133, 40.32663895, 40.32663895, 38.44078854,
       35.92632133, 40.32663895, 39.69802215, 40.32663895, 35.92632133,
       39.69802215, 40.64094735, 40.95525575, 40.64094735, 38.44078854,
       35.92632133, 40.95525575, 40.95525575, 40.32663895, 35.92632133,
       39.69802215, 40.64094735, 39.69802215, 40.32663895, 40.32663895,
       40.95525575, 40.95525575, 38.44078854, 39.69802215, 40.64094735,
       39.69802215, 35.92632133, 40.64094735, 39.69802215, 39.69802215,
       38.44078854, 40.32663895, 40.64094735, 40.64094735, 39.69802215,
       40.32663895, 40.32663895, 40.64094735, 40.64094735, 40.32663895,
       39.69802215, 38.44078854, 38.44078854, 39.69802215, 38.44078854,
       40.32663895, 38.44078854, 40.64094735, 40.64094735, 40.32663895,
       38.44078854, 39.69802215, 40.32663895, 40.64094735, 40.64094735,
       40.64094735, 40.32663895, 40.95525575, 40.64094735, 35.92632133,
       38.44078854, 35.92632133, 40.64094735, 39.69802215, 40.95525575,
       40.64094735, 35.92632133, 40.32663895, 40.32663895, 40.64094735,
       40.95525575, 40.64094735, 39.69802215, 40.95525575, 38.44078854,
       39.69802215, 40.32663895, 39.69802215, 35.92632133, 40.95525575,
       35.92632133, 40.64094735, 40.64094735, 40.32663895, 40.32663895,
       38.44078854, 35.92632133, 40.64094735, 39.69802215, 38.44078854,
       38.44078854, 40.95525575, 40.64094735, 38.44078854, 38.44078854,
       38.44078854, 39.69802215, 40.95525575, 38.44078854, 40.64094735,
       39.69802215, 40.95525575, 38.44078854, 39.69802215, 40.64094735,
       40.95525575, 40.95525575, 39.69802215, 35.92632133, 39.69802215,
       40.95525575, 35.92632133, 40.64094735])